### PR TITLE
Merge wiki into master

### LINKED ISSUE #9: As a contributor, I would like to submit pull requests instead of modifying the wiki directly
I was poking around with [clojurebridge/curriculum#45](https://github.com/ClojureBridge/curriculum/issues/45) and started meandering into stuff that was more related to organizing a ClojureBridge than teaching/taing at a clojurebridge.

As I was about to move that into this repo, I realized that I would need to update the wiki, which has no peer-review process. 

I much prefer to submit changes through a peer-review process, as it:

1. Exposes a signal to other collaborators that content has been changed, allowing them to stay abreast of informational changes
2. Allows people with more experience than I to provide feedback to improve the documentation, instead of me making changes that may run contrary to the experiences and principles of ClojureBridge staff.
3. Integrates nicely with [Github's web-editor](https://github.com/blog/1945-quick-pull-requests)

### PR DESCRIPTION
**Pull request by zspencer**
This:
0. Fixes #9
1. Moves the WIKI content into Master
2. Updates links
3. Cleans up trailing whitespace that the github editor likes to add.

I'd be happy to squash it down to a single commit if you prefer.

### CODE REVIEW

**Comment by seancorfield** [comment]
Wow! Thank you! This gets a big :+1: from me even without a detailed review.

**Comment by kpfell** [comment]
I don't actually have merge permissions on this repo, but would like to :+1: :+1: regardless, as I watched @zspencer put together the PR this afternoon, and it was epic. Haha.

**Comment by seancorfield** [comment]
Can we get another voice on this? I feel a little uncomfortable merging it since I was one the two :+1: so far... Either someone else should merge it or someone else should :+1: it and then I'll merge it.

**Comment by davidchambers** [comment]
:+1:

**Comment by seancorfield** [comment]
Thank you!

**Comment by davidchambers** [comment]
Should we now disable or delete the wiki?

**Comment by seancorfield** [comment]
I have updated the wiki home page to say the wiki has moved. There are quite a few links out there to pages on the wiki so I don't want to delete it yet.

I think a reasonable compromise would be to replace each page with a notice that says "This page has moved to ...link..." which we can do over the next few days/weeks as we get around to it.

That will allow folks who follow old links to find the new location and it will give us time to review our own material and update the links in other ClojureBridge material.

**Comment by seancorfield** [comment]
I have updated all wiki pages to point to their new home. We should review other ClojureBridge material for links to the `organizing` wiki and update those.

**Comment by davidchambers** [comment]
That was quick, @seancorfield!

**Pull request merged**
