### PR TITLE
Diversity FAQ.

### PR DESCRIPTION
**Pull request by mookerji**
/cc @kpfell @jgkite @yokolet

### CODE REVIEW

**Comment by kpfell** [comment]
Some brief copywriting change suggestions:

> For a workshop intending to introduce women to programming, ideally, there should be a strong presence of women both on the teaching staff and amongst the organizers. Given that, ClojureBridge exists to address an imbalance in the Clojure community, so a diverse teaching staff may not be possible in certain geographic areas. 
>
> Ultimately, it's important to be proactive about creating a diverse environment where possible, and that the environment created by a ClojureBridge workshop be inclusive of all participants.

**Comment by mookerji** [comment]
^^ @zahara .

**Comment by mookerji** [comment]
@kpfell done!

**Comment by zahara** [comment]
It would be good to add some pointers as to how to do this:

> Some ways to maximise the presence of women in the running of a ClojureBridge workshop are:
> * Invite local organisations for women in tech to advise/co-organise the event
> * Would any women you know who program in languages other than Clojure consider learning enough to be a TA?  This is particularly useful if they have previous experience teaching at a similar event like RailsBridge, Django Girls etc.
> * Are there women Clojure developers living in neighbouring cities who could help? (offer to pay their travel costs if possible)
> * Is there a Clojure/FP conference in your region which you could schedule ClojureBridge close to, so that conference delegates can volunteer?
> * If there's been a previous ClojureBridge near you, are there former students who could become TAs?
> * Make the most of the women you have, giving them leading roles in teaching and presenting

**Comment by kpfell** [comment]
@zahara :+1: to all you've written, but should we move that onto a separate wiki page?

Meaning, this page looks like it's currently geared more towards describing, overall, what a minimum viable workshop is. Should we be like, "For more information about increasing diversity of ClojureBridge instructors, see [page describing what you just said above]"?

**Comment by zahara** [comment]
Yeah, I was considering a separate page - the points could be expanded on and added to that way.

**Comment by yokolet** [comment]
It looks everything is ready. I don't have any object to @mookerji 's pull request and @zahara 's suggestion. I like "If there's been a previous ClojureBridge near you, are there former students who could become TAs?"

I'd like to add the sentences below to somewhere.

"Even though the first workshop couldn't make good gender balance on the teaching staff, the second, third... workshop may solve this problem. Don't disappoint to the first workshop's gender imbalance. Continue organizing will make the change."

**Comment by mookerji** [comment]
Thanks for the feedback. I had a slightly different iteration of this where this was in a FAQ-like document, and it seems like this is probably the best place to put that. I'll definitely add in @zahara and @yokolet 's addenda.

**Comment by mookerji** [comment]
Ack, sorry for neglecting this. I added it as an actual FAQ.

**Comment by yokolet** [comment]
:+1:

**Comment by zahara** [comment]
:+1:

**Pull request merged**
