### PR TITLE
Update list of current board members

### PR DESCRIPTION
**Pull request by kpfell**
Removed Bridget, Maggie, and Jennifer from the list, as they've since rolled off the board. :wave: 
Added Ali and Buro to the list, who have since joined the board! :tada: 
Added nicknames for Katherine and Bhaskar, who mostly go by kf and Buro.

Also, alphabetized the list of names--were they in some formal order before?

### CODE REVIEW

**Comment by seancorfield** [comment]
Feel free to remove me as I'm also rolling off at the end of the month.

**Comment by bridgethillyer** [comment]
:+1:

**Comment by seancorfield** [comment]
Consider that a :+1: from me above.

**Comment by kpfell** [comment]
@seancorfield Bah, alright, done. :wink:

**Comment by seancorfield** [comment]
Is there a "+2"? :)

**Comment by kpfell** [comment]
@bridgethillyer Do you have write access to this repo, or...?

**Comment by seancorfield** [comment]
In the absence of merge activity from anyone else, I acted on all those pluses (including mine).

**Pull request merged**
