### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by MaxMartin**
All over the dang place. Also updated a couple of things.

### CODE REVIEW

**Comment by seancorfield** [comment]
Should sample budget link to Sample-budget.md (rather than Money-Things.md)?

Also, there seem to be a number of changes from linking to parts of Workshop-Planning-Tasks.md to individual pages instead. Do we want to direct people into the overview document first, and then provide links to more detailed pages from there (status quo) or start linking directly to those pages (change of flow)?

**Comment by MaxMartin** [comment]
@seancorfield Sample-budget.md and Money-Things.md appear to mostly be duplicates of each other; if it's alright with you, I think they should be condensed into one file.

The only change I can find where I moved from linking to the workshop planning tasks page to an individual page was [this one](https://github.com/ClojureBridge/organizing/pull/18/files#diff-382c3810ffe8f744b71527e5d81f9d8bR25) regarding the class level grouping; did I miss more? I think an acceptable middle way here would be to have that part of the workshop planning tasks guide link to the full class grouping guide doc. I'll try pushing something like that.

**Comment by MaxMartin** [comment]
@seancorfield let me know if things look better after the new commit I just added :)

**Comment by seancorfield** [comment]
Two CB folks will need to review and give thumbs up for this to be merged.

I didn't realize Sample-budget.md and Money-Things.md were so nearly identical. Good catch. I'll take a closer look at the other changes when I get some free time later this week.

Thank you again for helping improve the organizing docs!

**Comment by seancorfield** [comment]
No action in six and a half years -- and the PR now has merge conflicts -- so I'm closing this.

**Pull request closed without merging**
